#=================================================
# https://github.com/sidpixel/lede
# Description: Build OpenWrt using GitHub Actions
# License: MIT
# Author: sidpixel
#=================================================

name: 8632.yml

on:
  release:
    types: [published]
  push:
    branches: 
      - main
    paths:
      - '8632.config'
      - 'ready.sh'
      - 'feeds.conf.default'
      - '.github/workflows/8632.yml'

  schedule:
    - cron: 21 1 1 */1 *
env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-22.03
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: 8632.config
  OS_ARCH: X86_32
  READY_SH: ready.sh
  RELEASE_VERSION: 22.03

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment and space clean
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /imagegeneration /opt  /usr/local/aws* /usr/local/julia* /usr/share/swift* /usr/share/sbt* /usr/local/share/chromium* /usr/local/share/powershell* /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
        docker rmi `docker images -q`
        sudo -E apt-mark hold grub-efi-amd64-signed
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev patch unzip lib32gcc-s1 libc6-dev-i386 subversion flex node-uglify gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils  libelf-dev autoconf automake libtool autopoint device-tree-compiler libuv1-dev python3.6 zlib1g-dev upx-ucl node-uglify antlr3 gperf wget swig rsync
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone source code
      run: |
        df -hT $PWD
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

    - name: Load custom feeds and Load custom configuration
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE  openwrt/.config
        chmod +x $READY_SH
        $GITHUB_WORKSPACE/$READY_SH

    - name: Update feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds clean
        ./scripts/feeds update -a
        ./scripts/feeds install -a


    - name: Download package
      working-directory: ./openwrt
      run: |
        make defconfig
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    
    - name: Compile the firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread compile"
        make -j$(nproc) V=s


    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Organize files
      run: |
        rm -rf ./artifact/
        mkdir -p ./artifact/
        mv openwrt/bin/targets/x86/64/*combined-efi.img* ./artifact/
        mv openwrt/bin/targets/x86/64/*.manifest ./artifact/
        cd ./artifact/
        ls -Ahl
        gzip -d *.gz && exit 0
        gzip --best *.img
        ls -Ahl
        
    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      with:
        name: openwrt-firmware
        path:  ./artifact/

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: OpenWRT-$OS_ARCH-$(date +%Y%m%d%H%M)-${{ env.RELEASE_VERSION }}
        files: ./artifact/*.gz
