#=================================================
# https://github.com/sidpixel/lede
# Description: Build OpenWrt using GitHub Actions
# License: MIT
# Author: sidpixel
#=================================================

name: test.yml

on:
  release:
    types: [published]
  push:
    branches: 
      - main
    paths:
      - '.github/workflows/test.yml'

  schedule:
    - cron: 21 21 1 */1 *
env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-22.03
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: 8632.config
  OS_ARCH: X86_32
  READY_SH: ready.sh
  RELEASE_VERSION: 22.03

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment and space clean
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        
        sudo -E timedatectl set-timezone "Asia/Shanghai"

    - name: Clone source code
      run: |

        df -hT $PWD
        git clone  -b $REPO_BRANCH $REPO_URL openwrt

    - name: Load custom feeds and Load custom configuration
      working-directory: ./openwrt
      run: |
        #mv $GITHUB_WORKSPACE/$FEEDS_CONF feeds.conf.default
        bash -x $GITHUB_WORKSPACE/$READY_SH
        ls
        cat feeds.conf.default    

    - name: load the  feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds clean 
        ./scripts/feeds update -a
        ./scripts/feeds install -a


    - name: create default config  package
      working-directory: ./openwrt
      run: |
        mv -f  $GITHUB_WORKSPACE/$CONFIG_FILE  .config
        make defconfig -j$(nproc)

    


   
    - name: Organize files
      run: |
        rm -rf ./artifact/
        mkdir -p ./artifact
        
        cp -rf openwrt/.config artifact/config8632
        cd ./artifact/
        gzip --best *
        ls -Ahl

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      with:
        name: openwrt-firmware
        path:  artifact/