#=================================================
# https://github.com/sidpixel/lede
# Description: Build OpenWrt using GitHub Actions
# License: MIT
# Author: sidpixel
#=================================================

name: test.yml

on:
  release:
    types: [published]
  push:
    branches: 
      - main
    paths:
      - '.github/workflows/test.yml'

  schedule:
    - cron: 21 11 1 */1 *
env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-22.03
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: 8632.config
  OS_ARCH: X86_32
  READY_SH: ready.sh
  RELEASE_VERSION: 22.03

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment and space clean
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
 
        sudo -E timedatectl set-timezone "Asia/Shanghai"

    - name: Clone source code
      run: |
        df -hT $PWD
        mkdir -p openwrt/bin/targets/x86/generic/test
        #git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

    - name: Load custom feeds and Load custom configuration
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        cat openwrt/feeds.conf.default
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE  openwrt/.config
        ls -Ahl openwrt/
        chmod +x $READY_SH
        bash -x $GITHUB_WORKSPACE/$READY_SH

    - name: Clone source code
      run: |
        df -hT $PWD
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

    - name: Load custom feeds and Load custom configuration
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE  openwrt/.config
        ls -Ahl openwrt/
        chmod +x $READY_SH
        bash -x $GITHUB_WORKSPACE/$READY_SH

    - name: Update feeds
      working-directory: ./openwrt
      run: |
        ls -Ahl
        ./scripts/feeds clean 
        ./scripts/feeds update -a
        ./scripts/feeds install -a


    

 
