name: test

on:
  push:
    branches: 
      - main
    paths:
      - '.github/workflows/test.yml'

jobs:
  check_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: sys info
        run: |
          brew install coreutils diffutils findutils gawk gnu-getopt gnu-tar grep wget quilt xz
          df -h