#=================================================
# https://github.com/sidpixel/lede
# Description: Build OpenWrt using GitHub Actions
# License: MIT
# Author: sidpixel
#=================================================

name: test.yml

on:
  release:
    types: [published]
  push:
    branches: 
      - main
    paths:
      - '.github/workflows/test.yml'

  schedule:
    - cron: 21 21 1 */1 *
env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-22.03
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: 8632.config
  OS_ARCH: X86_32
  READY_SH: ready.sh
  RELEASE_VERSION: 22.03

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
  
    - name: Initialization environment and space clean
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E timedatectl set-timezone "Asia/Shanghai"


    - name: Organize files
      run: |
        rm -rf ./artifact/
        mkdir -p ./artifact
        rm -rf $(find openwrt/bin/targets/*/*/ -type d -name "packages")
        #cp -rf $(find openwrt/bin/packages/ -type f -name "*.ipk") artifact/package/
        cp -rf $(find openwrt/bin/targets/*/*/ -type f -name "*.buildinfo" -o -name "openwrt.*" ) artifact/
        cd ./artifact/
        gzip --best *
        ls -Ahl

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      with:
        name: openwrt-firmware
        path:  artifact/

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: OpenWRT-${{ env.OS_ARCH }}-${{ env.FILE_DATE }}-${{ env.RELEASE_VERSION }}
        files: artifact/*



      
  


    

 
