#=================================================
# https://github.com/sidpixel/lede
# Description: Build OpenWrt using GitHub Actions
# License: MIT
# Author: sidpixel
#=================================================

name: test.yml

on:
  release:
    types: [published]
  push:
    branches: 
      - main
    paths:
      - '.github/workflows/test.yml'

  schedule:
    - cron: 21 21 1 */1 *
env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-22.03
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: 8632.config
  OS_ARCH: X86_32
  READY_SH: ready.sh
  RELEASE_VERSION: 22.03

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
  
    - name: Initialization environment and space clean
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E timedatectl set-timezone "Asia/Shanghai"
        echo "FILE_DATE=$(date +%Y%m%d%H%M)" >>"$GITHUB_ENV"
        sudo apt list|grep "python-docutils"



      
  


    

 
