name: Clean Up Workflow Runs

on:
  workflow_dispatch:  # 可以手动触发此工作流程

jobs:
  cleanup:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: sys info
        run: |
          nproc
          lscpu
