name: test

on:
  push:
    branches: 
      - main
    paths:
      - '.github/workflows/test.yml'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: sys info
        run: |
          sysctl -n machdep.cpu.brand_string
          sysctl -n hw.ncpu
